### ISSUE TITLE
Error "command 'language-julia.executeJuliaCodeInREPL' not found" reappears in recent versions

### ISSUE THREAD

**Issue by fplk** [julia-vscode/julia-vscode#1548]
The error reported in https://github.com/julia-vscode/julia-vscode/issues/412 also appears for me on 1.0.1. Someone in the thread mentioned it happened on v0.16.11 as well. My initial problem was that ran into the problem described independently here: https://discourse.julialang.org/t/missing-reference-warnings-with-julia-in-vs-code/31321 i.e. using statements were not resolved properly and led to hundreds of yellow warnings inside the editor. So I removed it and manually upgraded to 1.0.1 via VSIX, but now I get "command 'language-julia.executeJuliaCodeInREPL' not found" when I try to execute anything via Ctrl+Enter. This is on Ubuntu 20.04 with Julia 1.3.1 and VSCodium 1.47.3.

Side question: Do we still have to install the regular extension when using Julia Insider? I noticed that if I install both it seems to work.

**Comment by pfitzseb** [comment]
Sounds like something went wrong in the (un)install process.
Also, no, don't install the normal and insider extension alongside each other.

**Comment by davidanthoff** [comment]
I'm pretty sure that this error happens if our julia detection algorithm crashes. We _really_ need crash reporting for the extension code itself...

**Comment by davidanthoff** [comment]
Yes, but without crash reporting it is kind of unclear why it doesn't succeed :) I'll dust up the crash reporting for `activate`, I had that pretty much ready already.

**Comment by nhavt** [comment]
I just got this issue :(. Could anymore please tell me know to fix this issue?

**Comment by jespermartinsson** [comment]
I got the same issue with VS code 1.51.1 and julia language support 1.0.10 (and julia 1.5.2). I downgraded julia support until the issue disappeared and it seems like version 0.15.40 works but the issue appears in 0.16.7, if that helps tracking it down.

**Comment by davidanthoff** [comment]
We (hopefully) made this whole thing more robust, so I'm going to assume that this is fixed. If not, please reopen this issue.

**Comment by tsolewski** [comment]
I still have this problem reporting "Running the contributed command: 'language-julia.executeFile' failed." error when trying to execute some julia code. I already tried downgrading julia support, but it didn't help. Have you got any updates on this issue?

**Comment by pfitzseb** [comment]
That's a very different issue. Do you have crash reporting enabled?

**Comment by tsolewski** [comment]
Yes, I do. However I somehow managed to solve it (at least this error does not appear anymore). What I did was, as I already had configured path for Julia, I adjusted julia executable path in preferences settings to just 'julia' instead of the previously used full julia directory. This is on windows, not ubuntu as fplk's

**Comment by dnavarrosalvador** [comment]
same issue to me, exactly same message, using MacOS 10.15.7, Julia 1.4.2 - windows workaround didn't work

**Comment by dnavarrosalvador** [comment]
Solved, it was just PATH to julia exec mistyped

**Comment by adamhsparks** [comment]
I'm having this on one of my two MacBooks. I sync my VS Code settings between them and have the same version of Julia installed on both.

On my M1 MacBook Pro, this extension works fine.

On my M1 MacBook Air, this extension gives me this error, `command 'language-julia.executeJuliaCodeInREPL' not found`.

I'm at my wits' end trying to sort this out I can't find any reason for it to not work. It seems that it stopped sometime recently, not sure when since I don't use the Air as much for this work.

**Comment by oizin** [comment]
@adamhsparks I had this issue on an M1 MacBook, the REPL extension suddenly stopped working after I got a notification about language server I didn't read carefully. It was solved by installing the Julia LanguageServer package.

**Comment by adamhsparks** [comment]
I had done that before passing in this issue. It wasn’t that. But it did resolve itself. I have no idea how. But it’s happily working for me again.
