### ISSUE TITLE
"Possible method call error" in reexported functions?

### ISSUE THREAD

**Issue by dact221** [julia-vscode/julia-vscode#1576]
Hi

I'm trying to write some simple code, but the linter warns "possible method call errors" even for functions that I call correctly, e.g. `randn`.

Look that the linter correctly warns for `length` without arguments because there is no such method. On the other hand, the `randn` function gets highlighted on both valid methods.

The linter reports "`Base.randn` is a `Function`. **0** methods for function `Base.randn`", but I'm able to call the 13 methods of `randn`  in the REPL without importing any module.

I found that importing the `Random` module is a workaround in VS Code.

The problem is present in other modules like StatsPlots.jl for the function `plot!` that is reexported from Plots.jl.

- VSCode v1.47.3
- Julia extension v1.0.2

![image](https://user-images.githubusercontent.com/35376194/89437661-7bd00b00-d70d-11ea-9bcd-90a54149eb3a.png)

**Comment by fbanning** [comment]
I have the same problem all the time and would love for these messages to stop occuring. :)

**Comment by gnadt** [comment]
Also getting this issue in VS Code, but `import Random` not seeming to help

**Comment by lindnemi** [comment]
Same error for me. Unfortunately this makes the linter pretty much unusable for me since i use `randn` a lot.

**Comment by dact221** [comment]
Hi, is there any update? Does [StaticLint.jl issue #256](https://github.com/julia-vscode/StaticLint.jl/issues/256) have something to do with this issue?

**Comment by drandran12** [comment]
Same problem here

**Comment by Thermoflux** [comment]
I have the same problem.
`nrow(::Dataframe)`  shows the lint message, but the code runs fine. 
eg: 
` using CSV`
`using DataFrames`
`data = CSV.read("datafile.csv",DataFrame)`
`print(nrow(data))`
Last statement shows "Possible method call error" on "nrow".

**Comment by chmathys** [comment]
Also a problem here. All of this code works, so these are non-problems being flagged as problems.

<img width="345" alt="image" src="https://user-images.githubusercontent.com/19826429/163226665-7090011c-5379-4e7e-be07-8b57a84e966b.png">

**Comment by mmaehring** [comment]
I don't know if I contribute anything here, but I have the same problem as well. 
![image](https://user-images.githubusercontent.com/83184208/166291633-4e50f860-9830-467a-b538-160124d1a35a.png)

Again, all this code works perfectly fine.

**Comment by 93401** [comment]
Any news on this? I still see this problem and it is really annoying, mostly while plotting.

Julia vscode extension = 1.7.5

Julia Version 1.8.0
Commit 5544a0fab76 (2022-08-17 13:38 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: 16 × Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 8 on 8 virtual cores
Environment:
  JULIA_NUM_THREADS = auto
  JULIA_EDITOR = code

**Comment by TheFibonacciEffect** [comment]
Is there a way to turn off these error squiggles?

**Comment by pfitzseb** [comment]
Disabling the `julia.lint.call` setting should do the trick.

**Comment by evanphilip** [comment]
@TheFibonacciEffect as @pfitzseb pointed out, adding the following to `settings.json` will remove the squiggles for now:

```json
    "julia.lint.call": false  
```

**Comment by evanphilip** [comment]
I don't seem to have this bug anymore!
![image](https://user-images.githubusercontent.com/35814742/198262884-497bb4b7-6e85-46ba-a0e1-455fc632c1d8.png)

- VSCode 1.72.2
- Julia Extension v1.38.2
- Julia 1.8.2

Could one of you verify? @93401 @nathanrboyer

**Comment by 93401** [comment]
No change for me. Still get bogus warnings.

I am on an Intel Mac, with same versions as @evanphilip

**Comment by 93401** [comment]
Example below:

![Image 10-27-22 at 12 10 PM](https://user-images.githubusercontent.com/109233612/198378553-04be7f96-d6dc-467b-86bb-f94090ba9d38.jpeg)

**Comment by nathanrboyer** [comment]
I used to see method call errors with `plot` calls, but I don't after updating. I'm on Windows 11.
![image](https://user-images.githubusercontent.com/65452054/198386326-0e74dcd0-14ce-4633-b05b-ddad54c63f74.png)

**Comment by 93401** [comment]
@nathanrboyer This is strange. Maybe a Mac issue?

I am on macOS 12.6.1.

Here is a screenshot of my example, without the pop-up in the way.

<img width="471" alt="Screen Shot 2022-10-27 at 1 28 21 PM" src="https://user-images.githubusercontent.com/109233612/198391359-58c00534-49f5-4334-bc94-0bd9c3369c96.png">

**Comment by 93401** [comment]
It got quiet here.

Any news on this issue? I still have the issue on:

Intel Mac
macOS 12.6.1
VSCode  1.73.1
Julia Extension 1.38.2

**Comment by xkhainguyen** [comment]
> ```json
> "julia.lint.call": false  
> ```

Just do this.

**Comment by 93401** [comment]
Thanks, @xkhainguyen.

I do like lint when it works so I’d rather not disable it.

But a broken linter might be worse than no linter at all, I guess.

**Comment by 93401** [comment]
This problem persists for me.

Intel Mac
macOS 13.1
VSCode 1.74.3
Julia Extension 1.38.2
Julia 1.8.5

![vscode - 1](https://user-images.githubusercontent.com/109233612/214913715-7f743652-a5e8-4418-84f3-fda65136c86c.jpeg)

**Comment by jcbritobr** [comment]
Also happens for me.

![image](https://user-images.githubusercontent.com/6579862/215296173-ee6ddfa3-9a82-47ec-bf4a-aa01e4c3b0b4.png)


Julia Version 1.8.5
Commit 17cfb8e65e (2023-01-08 06:45 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 12 × Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 12 virtual cores

**Comment by 93401** [comment]
This seems to be fixed for me now.

Both Intel Mac and M1 Mac

macOS 13.3.1(a)
VSCode 1.78.1
Julia Extension 1.38.2
Julia 1.9.0

**Comment by jcbritobr** [comment]
Happens to me in fedora 38 x86_64
Julia 1.9

![image](https://github.com/julia-vscode/julia-vscode/assets/6579862/365bdc13-3e4e-4810-abe2-84d2d4c2b715)

I think I'll give up the linter for now.

**Comment by cadaverous-lives** [comment]
I am also experiencing this issue on macOS:
<img width="747" alt="image" src="https://github.com/julia-vscode/julia-vscode/assets/53010588/feb37464-82c3-4f75-b723-4dfeab370c61">
macOS: 13.4
vscode: 1.78.2
julia: 1.9.0
julia extension: 1.47.2

**Comment by fduple** [comment]
Add to your file:
```using Plots: plot, plot!     # Workaround for bug in vscode linter```

**Comment by mackeyma** [comment]
thanks! that works for me on a new MacBook Pro M2 Max

**Comment by pappataci** [comment]
Thanks @fduple : worked for me, too

**Comment by rben01** [comment]
This is still generally an issue for me. For instance, `nrow` from `DataFrames.jl` is underlined even when called, correctly, as `nrow(df)`. Here is what the hover info contains:

```
Possible method call error.Julia(IncorrectCallArgs)
---
nrow(t)
Return the number of rows of table t.

DataAPI.nrow is a Function. 0 methods for function DataAPI.nrow
```

**Comment by brychcy** [comment]
My bugfix has been merged, but this has not been released yet.

**Comment by brychcy** [comment]
But actually there is a workaround: 
The problem appears if the DataFrames package is indexed together with packages to whose functions it adds methods.
If it is indexed alone, the cache file is complete.
So quit VSCode, remove the cache file (exact location depends on Operating system and version of the package), e.g. on MacOS
```
rm "$HOME/Library/Application Support/Code/User/globalStorage/julialang.language-julia/symbolstorev5/D/DataFrames_a93c6f00-e57d-5684-b7b6-d8193f3e46c0/v1.5.0_aa51303df86f8626a962fccb878430cdb0a97eee.jstore"
```
Then start VSCode again and it should reindex just the DataFrames package and the errors should go away.

**Comment by RomeoV** [comment]
@brychcy I installed `add SymbolServer#master` and now the problem is fixed, presumably thanks to your fix. Thanks!
Note that I'm using emacs, not VSCode. I'm not sure how to install master using VSCode.

**Comment by 93401** [comment]
This bug is still in Julia 1.10



![6E54ED41-988D-4A91-B513-D54780498A54](https://github.com/julia-vscode/julia-vscode/assets/109233612/a146f4f3-bf1a-4164-bccc-f57180837e38)



macOS: 14.2.1
vscode: 1.85.1
julia: 1.10.0
julia extension: 1.65.2

**Comment by leoflotor** [comment]
> This bug is still in Julia 1.10
> 
> ![6E54ED41-988D-4A91-B513-D54780498A54](https://private-user-images.githubusercontent.com/109233612/293075728-a146f4f3-bf1a-4164-bccc-f57180837e38.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NDA3MjQsIm5iZiI6MTcwMzc0MDQyNCwicGF0aCI6Ii8xMDkyMzM2MTIvMjkzMDc1NzI4LWExNDZmNGYzLWJmMWEtNDE2NC1iY2NjLWY1NzE4MDgzN2UzOC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjhUMDUxMzQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWNjMmZiODRlYzdlOTZjMDY2OGQ5YmYyNzZhNzAxYzlmNDE5MTU4NDA5MmE0ZTI1ZTkzNTZmMTdjYmRiMjk3MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.b8UGiccLTT7eohDENyuONH9pFse0YE0_cPxsJ3vEMkA)
> 
> macOS: 14.2.1 vscode: 1.85.1 julia: 1.10.0 julia extension: 1.65.2

I have the same problem but I am using Helix. 

This happens in functions like `sort`, `sort!`, `joinpath`, `isfile`, and so on.

If I roll back to julia 1.9.4 the errors disappear.

**Comment by pfitzseb** [comment]
Should be fixed by https://github.com/julia-vscode/SymbolServer.jl/pull/308.
