### ISSUE TITLE
'language-julia.executeCodeBlockOrSelectionAndMove' command (Alt+Enter) not working

### ISSUE THREAD

**Issue by casasgomezuribarri** [julia-vscode/julia-vscode#1967]
I always use `Alt`+`Enter` to execute code, mainly because I like having the outputs reported on the editor to easily access objects in long files. 

I have never had a problem with this until today: if I open a Julia file and press `Alt`+`Enter`, I get the error
```
ERROR: LoadError: EOFError: read end of file
Stacktrace:
 [1] read(::IOStream, ::Type{Int64}) at .\iostream.jl:361
 [2] parse_cache_header(::IOStream) at .\loading.jl:1323
 [3] stale_cachefile(::String, ::String) at .\loading.jl:1402
 [4] _require_search_from_serialized(::Base.PkgId, ::String) at .\loading.jl:757
 [5] _require(::Base.PkgId) at .\loading.jl:1006
 [6] require(::Base.PkgId) at .\loading.jl:927
 [7] require(::Module, ::Symbol) at .\loading.jl:922
 [8] include(::Module, ::String) at .\Base.jl:377
 [9] exec_options(::Base.JLOptions) at .\client.jl:288
 [10] _start() at .\client.jl:484
in expression starting at c:\Users\ivica\.vscode\extensions\julialang.language-julia-1.1.26\scripts\terminalserver\terminalserver.jl:4
```
But that is only true for the first time I do it, if I press `Alt`+`Enter` again, I get a pop-up message on the lower right corner: 
`Running the contributed command: 'language-julia.executeCodeBlockOrSelectionAndMove' failed.`

`Shift`+`Enter `or `Ctrl`+`Enter` seem to work fine and successfully evaluate any given line, but they don't seem to work with `begin` blocks. 

**Version info**
VSCode: v.1.53.2
Julia: v.1.4.2
OS: Windows 10
julialang: v.1.1.26

**Comment by pfitzseb** [comment]
Can you try deleting the `C:\Users\ivica\.julia\compiled\v1.4\VSCodeServer` dir? If that's not enough, maybe try deleting the whole compile cache (`C:\Users\ivica\.julia\compiled\v1.4\`).

**Comment by casasgomezuribarri** [comment]
Deleting the `C:\Users\ivica\.julia\compiled\v1.4\VSCodeServer` folder fixed it! Thanks a lot 🙌

**Comment by JianghuiDu** [comment]
I have exactly the same issue. It just appeared suddenly while working perfectly the day before. I deleted the compiled files of VSCodeServer as well as all the other packages, but it didn't work. I deleted VSCode and all its setting, not working either. Any thoughts?

**Comment by mmikhasenko** [comment]
The issue got more regular somehow. Usually, it is solved on the fifth restart of the REPL.

**Comment by JianghuiDu** [comment]
I've uninstalled both julia and vscode, cleaned everything, and reinstalled everything. Still not working...

**Comment by mmikhasenko** [comment]
It takes a few opening and closing of Julia REPL in vs code before it synchronizes, but eventually, it works.
It might be something different for me.

**Comment by JianghuiDu** [comment]
I've tried 30 times... no luck... What do you mean "synchronize". For me `Control+Enter` works but not `Alt+Enter` nor `Shift+Enter`...
