### ISSUE TITLE
Plots appear in new tab in same editor group as the generating code instead of in a new editor group

### ISSUE THREAD

**Issue by oscarrutt** [julia-vscode/julia-vscode#2618]
I'm using the extension in Visual Studio Code on a Mac.

Until approximately 1-3 days ago, making a first plot with Julia would create a new editor group and a new tab within the new group, then place the first plot in the new tab/group. Subsequent plots went to the same tab with an ability to flip through them with a click or key combination.

Now, it's all broken. Plots appear in a new tab in the _same_ editor group as the generating code so that it is not possible to view the graphs at the same time as viewing the code. I figure, OK, so maybe this is a bad idea for a new feature, so I dragged the tab so that a new editor group is formed and the plot tab is now in that new group. Then I make another plot. The former new group is gone and the plot tab is back where it originally appeared, in the same editor group as my code.

This behavior is in both versions 1.5.5 and 1.5.6. It is possible that updating VSC from 1.6.2 to 1.6.3 caused the problem, since that is about when I first noticed it.

**Comment by yha** [comment]
Downgrading VSCode to 1.6.2 (by downloading it directly from https://code.visualstudio.com/updates/v1_62) seems to fix it for now.

**Comment by pfitzseb** [comment]
This is fixed in 1.5.7 of the extension (currently only in the insiders channel). Please give that a go and report back.

**Comment by Samuel3008** [comment]
I just tried 1.5.7 and this still happens.

**Comment by pfitzseb** [comment]
What version of VS Code are you on? I cannot repro the issue on VS Code 1.64.0 and 1.5.7 of the extension.

**Comment by Samuel3008** [comment]
1.63.0

**Comment by pfitzseb** [comment]
Ok, so this presumably works fine on 1.62 and earlier as well as 1.64 and later.

**Comment by pfitzseb** [comment]
I tried reproducing this with julia-insiders on VSCode 1.63 and 1.64 and can't.

**Comment by lmiq** [comment]
For me, once I split the plot pane to the right, it stays there. If I close it and plot again, it opens in the "wrong" place. Not sure if that is expected or if we want it to open where it was before.

**Comment by pfitzseb** [comment]
That's also something I can't reproduce on julia-insiders and VS Code 1.63.1 -- the plot pane always opens in the second column.

**Comment by MarekIgnaszak** [comment]
Problem still persists with julia-insiders and VS Code 1.63.1 on Linux. Downgrading VS Code to 1.62 fixed it for me.

**Comment by sheevy** [comment]
Win10 + VS Code 1.63.1 + julia-insider 1.5.7 => bug is fixed (i.e. plot opens in the second pane)

**Comment by lmiq** [comment]
After vscode upgraded to 1.63.1 the bug came back for me even with Julia Insider (not sure which version, if 1.5.7 was released yesterday it may be the previous one). I had to downgrade to VScode 1.62.3 because in the middle of some heavy stuff.

**Comment by MarekIgnaszak** [comment]
Final update from my side: there's been a new release of VS Code 1.63.2 few hours ago and now, in combination with Julia insider (1.5.7), plots work as expected (but not in Julia 1.5.6). Many thanks for the fixes!

**Comment by sheevy** [comment]
On Win10: VSCode 1.63.2 and julia-insiders (1.5.7) *does not* fix the issue.

**Comment by casasgomezuribarri** [comment]
> On Win10: VSCode 1.63.2 and julia-insiders (1.5.7) _does not_ fix the issue.

yup same here

**Comment by tpoisot** [comment]
Pop OS!, VSCode 1.63.2 and extension 1.5.8 does not fix the issue either

**Comment by mchitre** [comment]
Seeing it on MacOS VScode 1.63.2 and ext 1.5.8 as well.

**Comment by pfitzseb** [comment]
Can you try 1.5.9-insiders? That should fix the bug for good, hopefully.

**Comment by yha** [comment]
I see the same issue with Insiders 1.5.9 on vscode 1.63.2. 
The workaround I described above also still works.

**Comment by glwhart** [comment]
> After vscode upgraded to 1.63.1 the bug came back for me even with Julia Insider (not sure which version, if 1.5.7 was released yesterday it may be the previous one). I had to downgrade to VScode 1.62.3 because in the middle of some heavy stuff.

Downgrading to 1.62.3 did the trick for me.

**Comment by pfitzseb** [comment]
There should be a new release of the extension out in a few minutes that seems to fix the issue for me.

**Comment by oscarrutt** [comment]
Seems to be working now! The first time I made a plot after upgrading to 1.5.10 I had to manually drag the plot pane from editor group 1 to a new editor group, but after that it worked right, making the first plot in group 2, including after restarting VSC. I'm on VSC 1.63.0 on macOS.

**Comment by lmiq** [comment]
Confirming the fix here, VScode 1.63.2, 1.5.10 in Linux.
