### ISSUE TITLE
Highlight interpolation in cmd macros

### ISSUE THREAD

**Issue by jtrakk** [julia-vscode/julia-vscode#2632]
str macros get highlighted but cmd macros don't:

![image](https://user-images.githubusercontent.com/43392409/146310436-0d4e7da8-c182-4049-b2a4-3e29d4cac11d.png)

**Comment by Cyrannosaurus** [comment]
This is consistently bothering me and seems like a small fix, anyone have tips on how to do it or where to start?

**Comment by pfitzseb** [comment]
This is fixed on master:
![image](https://github.com/julia-vscode/julia-vscode/assets/6735977/2b43a50f-2545-4753-a218-269b07d25d9b)

**Comment by Cyrannosaurus** [comment]
![image](https://github.com/julia-vscode/julia-vscode/assets/70718730/e6102442-5384-4a42-a5c1-419534717294)
I'm still seeing it fail to register the interpolation. Julia-vscode preview version (I actually switched hoping to find this was fixed tho, I had the issue on develop as well). Julia version 1.9.0.

**Comment by Cyrannosaurus** [comment]
ah, and I'm using WSL :(

**Comment by pfitzseb** [comment]
That's not relevant, I think. This change is not in any released version of the extension.

**Comment by Cyrannosaurus** [comment]
My mistake. Thought master would be the current version of the extension.

**Comment by pfitzseb** [comment]
Nope. I'll hopefully get around to tagging a new version soon though :)

**Comment by Cyrannosaurus** [comment]
:) thanks
