### ISSUE TITLE
"The test process crashed while running this test"

### ISSUE THREAD

**Issue by jedforrest** [julia-vscode/julia-vscode#3055]
On my first time using this package, when I run any test I only get the error message "The test process crashed while running this test.", with no other detail given.

The entire file for my test was:
```julia
using TestItems

@testitem "Test for foo" begin
    x = 2
    @test x == 2
end
```

I am using Julia 1.8.0 and VSCode 1.71.0
```
(@v1.8) pkg> st
Status `C:\Users\jedfo\.julia\environments\v1.8\Project.toml`
  [336ed68f] CSV v0.10.4
  [a93c6f00] DataFrames v1.3.4
  [864edb3b] DataStructures v0.18.13
  [0c46a032] DifferentialEquations v7.3.0
  [31c24e10] Distributions v0.25.70
  [6b9d7cbe] GeneralizedGenerated v0.3.3
  [a98d9a8b] Interpolations v0.14.4
  [23fbe1c1] Latexify v0.15.16
  [91a5bcdd] Plots v1.31.7
  [438e738f] PyCall v1.94.1
  [d330b81b] PyPlot v2.11.0
  [1fd47b50] QuadGK v2.5.0
  [f3b207a7] StatsPlots v0.15.2
  [24249f21] SymPy v1.1.7
  [f8b46487] TestItemRunner v0.2.0
  [1c621080] TestItems v0.1.0
  [ade2ca70] Dates
  [37e2e46d] LinearAlgebra
  [9a3f8284] Random
```

This package looks really promising so I hope this can get fixed so I can start using it!

**Comment by davidanthoff** [comment]
Can you try again with the latest version of the extension? I fixed some errors, although this one might be different.

Can you also click the red circled button here:

![image](https://user-images.githubusercontent.com/1036561/188965253-fd00f47d-dc17-4214-b589-018096a82319.png)

And report whether that shows any output of interest?

**Comment by jedforrest** [comment]
Hi David,

I've run the test again, and while it still crashes, there is now some
meaningful output (printed below). It says that the Dev path does not
exist, which makes sense since I'm not running the file in my dev folder.

When I do run it in dev however, the test works perfectly! Is it a
requirement that all TestItems be run from a dev folder? If so, maybe a
warning or error message saying that is needed?

[ Info: The Julia Test Server is now connected to the Julia extension
  Activating new project at `C:\Users\jedfo\AppData\Local\Temp\jl_s3VXIx`
┌ Error: Some Julia code in the VS Code extension crashed
└ @ Main
c:\Users\jedfo\.vscode\extensions\julialang.language-julia-1.7.10\scripts\error_handler.jl:15
ERROR: Dev path `` does not exist.
Stacktrace:
  [1] pkgerror(msg::String)
    @ Pkg.Types
C:\Users\jedfo\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Pkg\src\Types.jl:67
  [2] handle_repo_develop!(ctx::Pkg.Types.Context,
pkg::Pkg.Types.PackageSpec, shared::Bool)
    @ Pkg.Types
C:\Users\jedfo\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Pkg\src\Types.jl:547
  [3] handle_repos_develop!(ctx::Pkg.Types.Context,
pkgs::Vector{Pkg.Types.PackageSpec}, shared::Bool)
    @ Pkg.Types
C:\Users\jedfo\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Pkg\src\Types.jl:626
  [4] develop(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec};
shared::Bool, preserve::Pkg.Types.PreserveLevel,
platform::Base.BinaryPlatforms.Platform, kwargs::Base.Pairs{Symbol,
Base.PipeEndpoint, Tuple{Symbol}, NamedTuple{(:io,),
Tuple{Base.PipeEndpoint}}})
    @ Pkg.API
C:\Users\jedfo\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Pkg\src\API.jl:211
  [5] develop(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.PipeEndpoint,
kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API
C:\Users\jedfo\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Pkg\src\API.jl:156
  [6] develop(pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API
C:\Users\jedfo\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Pkg\src\API.jl:145
  [7] #develop#14
    @
C:\Users\jedfo\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Pkg\src\API.jl:143
[inlined]
  [8] develop
    @
C:\Users\jedfo\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Pkg\src\API.jl:143
[inlined]
  [9] develop(; name::Nothing, uuid::Nothing, version::Nothing,
url::Nothing, rev::Nothing, path::String, mode::Pkg.Types.PackageMode,
subdir::Nothing, kwargs::Base.Pairs{Symbol, Union{}, Tuple{},
NamedTuple{(), Tuple{}}})
    @ Pkg.API
C:\Users\jedfo\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Pkg\src\API.jl:173
 [10] serve(conn::Base.PipeEndpoint, project_path::String,
package_path::String, package_name::String; is_dev::Bool,
crashreporting_pipename::Nothing)
    @ VSCodeTestServer
c:\Users\jedfo\.vscode\extensions\julialang.language-julia-1.7.10\scripts\packages\VSCodeTestServer\src\VSCodeTestServer.jl:144
 [11] serve(conn::Base.PipeEndpoint, project_path::String,
package_path::String, package_name::String)
    @ VSCodeTestServer
c:\Users\jedfo\.vscode\extensions\julialang.language-julia-1.7.10\scripts\packages\VSCodeTestServer\src\VSCodeTestServer.jl:140
 [12] top-level scope
    @
c:\Users\jedfo\.vscode\extensions\julialang.language-julia-1.7.10\scripts\testserver\testserver_main.jl:16
 [13] include(mod::Module, _path::String)
    @ Base .\Base.jl:419
 [14] exec_options(opts::Base.JLOptions)
    @ Base .\client.jl:303
 [15] _start()
    @ Base .\client.jl:522

Thanks,
Joshua

**Comment by davidanthoff** [comment]
I think the problem here is that the `@testitem` code is in a file that can't be associated clearly with a Julia project. In general, `@testitem` code must be in files that are in a folder that has at some point a parent folder with a `Project.toml` that is defining a Julia package. It seems to me that is not the case here?
