### ISSUE TITLE
the language server can't start with latest Julia nightly

### ISSUE THREAD

**Issue by nsajko** [julia-vscode/julia-vscode#3451]
This happened after updating to the latest Julia nightly, while everything worked fine with the nightly from a few days ago. I'm still able to "start REPL" from Code, but the language server is in a crash loop.

```julia-repl
julia> versioninfo()
Julia Version 1.11.0-DEV.761
Commit 9c581cd719f (2023-10-28 11:49 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × AMD Ryzen 3 5300U with Radeon Graphics
  WORD_SIZE: 64
  LLVM: libLLVM-15.0.7 (ORCJIT, znver2)
  Threads: 11 on 8 virtual cores
Environment:
  JULIA_NUM_PRECOMPILE_TASKS = 3
  JULIA_PKG_PRECOMPILE_AUTO = 0
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 8
```

```
  Activating project at `~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/environments/languageserver/fallback`
[ Info: Starting the Julia Language Server
ERROR: LoadError: (Core, Module)
Stacktrace:
  [1] error(s::Tuple{Module, DataType})
    @ Base ./error.jl:44
  [2] SymbolServer.FakeTypeName(x::Any; justname::Bool)
    @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/SymbolServer/src/faketypes.jl:43
  [3] _parameter(p::Any)
    @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/SymbolServer/src/faketypes.jl:73
  [4] SymbolServer.FakeTypeName(x::Any; justname::Bool)
    @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/SymbolServer/src/faketypes.jl:30
  [5] FakeTypeName
    @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/SymbolServer/src/faketypes.jl:17 [inlined]
  [6] symbols(env::Dict{Symbol, SymbolServer.ModuleStore}, m::Module, allnames::Base.IdSet{Symbol}, visited::Base.IdSet{Module}; get_return_type::Bool)
    @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/SymbolServer/src/symbols.jl:474
  [7] symbols
    @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/SymbolServer/src/symbols.jl:419 [inlined]
  [8] symbols(env::Dict{Symbol, SymbolServer.ModuleStore}, m::Nothing, allnames::Base.IdSet{Symbol}, visited::Base.IdSet{Module}; get_return_type::Bool)
    @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/SymbolServer/src/symbols.jl:479
  [9] symbols (repeats 4 times)
    @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/SymbolServer/src/symbols.jl:419 [inlined]
 [10] load_core(; get_return_type::Bool)
    @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/SymbolServer/src/symbols.jl:488
 [11] load_core()
    @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/SymbolServer/src/symbols.jl:485
 [12] top-level scope
    @ ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/SymbolServer/src/SymbolServer.jl:361
 [13] include
    @ Base ./Base.jl:523 [inlined]
 [14] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::String)
    @ Base ./loading.jl:2311
 [15] top-level scope
    @ stdin:3
in expression starting at /home/nsajko/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/SymbolServer/src/SymbolServer.jl:1
in expression starting at stdin:3
ERROR: LoadError: Failed to precompile SymbolServer [cf896787-08d5-524d-9de7-132aaa0cb996] to "/home/nsajko/.config/Code - OSS/User/globalStorage/julialang.language-julia/lsdepot/v1/compiled/v1.11/SymbolServer/jl_qMz96P".
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base ./loading.jl:2563
  [3] compilecache
    @ Base ./loading.jl:2429 [inlined]
  [4] (::Base.var"#1027#1028"{Base.PkgId})()
    @ Base ./loading.jl:2031
  [5] mkpidlock(f::Base.var"#1027#1028"{Base.PkgId}, at::String, pid::Int32; kwopts::@Kwargs{stale_age::Int64, wait::Bool})
    @ FileWatching.Pidfile ~/tmp/jl/jl/julia-9c581cd719/share/julia/stdlib/v1.11/FileWatching/src/pidfile.jl:95
  [6] #mkpidlock#6
    @ FileWatching.Pidfile ~/tmp/jl/jl/julia-9c581cd719/share/julia/stdlib/v1.11/FileWatching/src/pidfile.jl:90 [inlined]
  [7] trymkpidlock(::Function, ::Vararg{Any}; kwargs::@Kwargs{stale_age::Int64})
    @ FileWatching.Pidfile ~/tmp/jl/jl/julia-9c581cd719/share/julia/stdlib/v1.11/FileWatching/src/pidfile.jl:116
  [8] #invokelatest#2
    @ Base ./essentials.jl:931 [inlined]
  [9] invokelatest
    @ Base ./essentials.jl:926 [inlined]
 [10] maybe_cachefile_lock(f::Base.var"#1027#1028"{Base.PkgId}, pkg::Base.PkgId, srcpath::String; stale_age::Int64)
    @ Base ./loading.jl:3142
 [11] maybe_cachefile_lock
    @ Base ./loading.jl:3139 [inlined]
 [12] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:2027
 [13] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1872
 [14] #invoke_in_world#3
    @ Base ./essentials.jl:963 [inlined]
 [15] invoke_in_world
    @ Base ./essentials.jl:960 [inlined]
 [16] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1863
 [17] macro expansion
    @ Base ./loading.jl:1801 [inlined]
 [18] macro expansion
    @ Base ./lock.jl:267 [inlined]
 [19] __require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1762
 [20] #invoke_in_world#3
    @ Base ./essentials.jl:963 [inlined]
 [21] invoke_in_world
    @ Base ./essentials.jl:960 [inlined]
 [22] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1755
 [23] include
    @ Base ./Base.jl:523 [inlined]
 [24] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::String)
    @ Base ./loading.jl:2311
 [25] top-level scope
    @ stdin:3
in expression starting at /home/nsajko/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/LanguageServer/src/LanguageServer.jl:1
in expression starting at stdin:3


The Language Server failed to precompile.
Please make sure you have permissions to write to the LS depot path at
	/home/nsajko/.config/Code - OSS/User/globalStorage/julialang.language-julia/lsdepot/v1

┌ Error: Some Julia code in the VS Code extension crashed
└ @ Main ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/error_handler.jl:15
ERROR: Failed to precompile LanguageServer [2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7] to "/home/nsajko/.config/Code - OSS/User/globalStorage/julialang.language-julia/lsdepot/v1/compiled/v1.11/LanguageServer/jl_PhJzfY".
Stacktrace:
 [1] top-level scope
   @ ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/languageserver/main.jl:77
 [2] include(mod::Module, _path::String)
   @ Base ./Base.jl:523
 [3] exec_options(opts::Base.JLOptions)
   @ Base ./client.jl:318
 [4] _start()
   @ Base ./client.jl:569
[Error - 3:22:59 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 3:22:59 PM] Connection to server got closed. Server will restart.
true
[Error - 3:22:59 PM] Julia Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
  Activating project at `~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/environments/languageserver/fallback`
[ Info: Starting the Julia Language Server
ERROR: LoadError: (Core, Module)
Stacktrace:
  [1] error(s::Tuple{Module, DataType})
    @ Base ./error.jl:44
  [2] SymbolServer.FakeTypeName(x::Any; justname::Bool)
    @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/SymbolServer/src/faketypes.jl:43
  [3] _parameter(p::Any)
    @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/SymbolServer/src/faketypes.jl:73
  [4] SymbolServer.FakeTypeName(x::Any; justname::Bool)
    @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/SymbolServer/src/faketypes.jl:30
  [5] FakeTypeName
    @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/SymbolServer/src/faketypes.jl:17 [inlined]
  [6] symbols(env::Dict{Symbol, SymbolServer.ModuleStore}, m::Module, allnames::Base.IdSet{Symbol}, visited::Base.IdSet{Module}; get_return_type::Bool)
    @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/SymbolServer/src/symbols.jl:474
  [7] symbols
    @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/SymbolServer/src/symbols.jl:419 [inlined]
  [8] symbols(env::Dict{Symbol, SymbolServer.ModuleStore}, m::Nothing, allnames::Base.IdSet{Symbol}, visited::Base.IdSet{Module}; get_return_type::Bool)
    @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/SymbolServer/src/symbols.jl:479
  [9] symbols (repeats 4 times)
    @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/SymbolServer/src/symbols.jl:419 [inlined]
 [10] load_core(; get_return_type::Bool)
    @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/SymbolServer/src/symbols.jl:488
 [11] load_core()
    @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/SymbolServer/src/symbols.jl:485
 [12] top-level scope
    @ ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/SymbolServer/src/SymbolServer.jl:361
 [13] include
    @ Base ./Base.jl:523 [inlined]
 [14] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::String)
    @ Base ./loading.jl:2311
 [15] top-level scope
    @ stdin:3
in expression starting at /home/nsajko/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/SymbolServer/src/SymbolServer.jl:1
in expression starting at stdin:3
ERROR: LoadError: Failed to precompile SymbolServer [cf896787-08d5-524d-9de7-132aaa0cb996] to "/home/nsajko/.config/Code - OSS/User/globalStorage/julialang.language-julia/lsdepot/v1/compiled/v1.11/SymbolServer/jl_61SQ23".
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base ./loading.jl:2563
  [3] compilecache
    @ Base ./loading.jl:2429 [inlined]
  [4] (::Base.var"#1027#1028"{Base.PkgId})()
    @ Base ./loading.jl:2031
  [5] mkpidlock(f::Base.var"#1027#1028"{Base.PkgId}, at::String, pid::Int32; kwopts::@Kwargs{stale_age::Int64, wait::Bool})
    @ FileWatching.Pidfile ~/tmp/jl/jl/julia-9c581cd719/share/julia/stdlib/v1.11/FileWatching/src/pidfile.jl:95
  [6] #mkpidlock#6
    @ FileWatching.Pidfile ~/tmp/jl/jl/julia-9c581cd719/share/julia/stdlib/v1.11/FileWatching/src/pidfile.jl:90 [inlined]
  [7] trymkpidlock(::Function, ::Vararg{Any}; kwargs::@Kwargs{stale_age::Int64})
    @ FileWatching.Pidfile ~/tmp/jl/jl/julia-9c581cd719/share/julia/stdlib/v1.11/FileWatching/src/pidfile.jl:116
  [8] #invokelatest#2
    @ Base ./essentials.jl:931 [inlined]
  [9] invokelatest
    @ Base ./essentials.jl:926 [inlined]
 [10] maybe_cachefile_lock(f::Base.var"#1027#1028"{Base.PkgId}, pkg::Base.PkgId, srcpath::String; stale_age::Int64)
    @ Base ./loading.jl:3142
 [11] maybe_cachefile_lock
    @ Base ./loading.jl:3139 [inlined]
 [12] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:2027
 [13] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1872
 [14] #invoke_in_world#3
    @ Base ./essentials.jl:963 [inlined]
 [15] invoke_in_world
    @ Base ./essentials.jl:960 [inlined]
 [16] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1863
 [17] macro expansion
    @ Base ./loading.jl:1801 [inlined]
 [18] macro expansion
    @ Base ./lock.jl:267 [inlined]
 [19] __require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1762
 [20] #invoke_in_world#3
    @ Base ./essentials.jl:963 [inlined]
 [21] invoke_in_world
    @ Base ./essentials.jl:960 [inlined]
 [22] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1755
 [23] include
    @ Base ./Base.jl:523 [inlined]
 [24] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::String)
    @ Base ./loading.jl:2311
 [25] top-level scope
    @ stdin:3
in expression starting at /home/nsajko/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/packages/LanguageServer/src/LanguageServer.jl:1
in expression starting at stdin:3


The Language Server failed to precompile.
Please make sure you have permissions to write to the LS depot path at
	/home/nsajko/.config/Code - OSS/User/globalStorage/julialang.language-julia/lsdepot/v1

┌ Error: Some Julia code in the VS Code extension crashed
└ @ Main ~/.vscode-oss/extensions/julialang.language-julia-1.56.2-universal/scripts/error_handler.jl:15
ERROR: Failed to precompile LanguageServer [2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7] to "/home/nsajko/.config/Code - OSS/User/globalStorage/julialang.language-julia/lsdepot/v1/compiled/v1.11/LanguageServer/jl_PYU8AX".
```

**Comment by pfitzseb** [comment]
Probably fixed by https://github.com/julia-vscode/SymbolServer.jl/pull/276

**Comment by staticfloat** [comment]
FWIW I'm still hitting this.

**Comment by jbytecode** [comment]
I don't know why this issue is closed but the LanguageServer still doesn't start in nightly and alpha channels. Maybe it is of JuliaFormatter and SymbolServer?

**Comment by pfitzseb** [comment]
Because nightly is a moving target and something [else](https://github.com/julia-vscode/CSTParser.jl/pull/386) broke. This should be fixed by the next release.
