### ISSUE TITLE
A bunch of Base identifiers are said to be "Missing reference"

### ISSUE THREAD

**Issue by KristofferC** [julia-vscode/julia-vscode#794]
This is when editing files in Base if that matters:

<img width="422" alt="Screenshot 2019-07-18 at 16 02 18" src="https://user-images.githubusercontent.com/1282691/61463853-8b9b7680-a975-11e9-9fa8-5feb75cfe14b.png">
<img width="709" alt="Screenshot 2019-07-18 at 16 02 10" src="https://user-images.githubusercontent.com/1282691/61463858-8dfdd080-a975-11e9-8189-e76c5d801e5c.png">

**Comment by ZacLN** [comment]
For some reason I though Core wasn't imported into a baremodule... fixed here: https://github.com/julia-vscode/StaticLint.jl/commit/10032ba9da03eb10fdd8a7d4fdce252e74a641f1

**Comment by davidanthoff** [comment]
Then we can close this, right?

**Comment by KristofferC** [comment]
Still doesn't seem completely fixed

<img width="624" alt="Screenshot 2019-07-18 at 21 47 29" src="https://user-images.githubusercontent.com/1282691/61487245-b0a7dd80-a9a5-11e9-81fb-2b94c23bdb53.png">

**Comment by KristofferC** [comment]
The `bitcast´ and company are intrinsics so that could be why they are not found.

Note sure about the `widenconst`.

**Comment by KristofferC** [comment]
One way to repro is just to open the julia source folder and look at the thousands of missing references reported.

**Comment by davidanthoff** [comment]
I'd say we fix it for v0.12.1? I _really_ want to ship a version before the weekend :)

**Comment by ZacLN** [comment]
Yep that should be the plan. I'm going to start working my way through /base to get all that symbol resolution working

**Comment by darrickyee** [comment]
I'm assuming this is the same issue?  The squigglies are "Missing reference" errors.  (Note the code runs fine)

![errors](https://user-images.githubusercontent.com/18172544/62245925-9d870b80-b3b0-11e9-8641-2a89722d6e62.png)

**Comment by ZacLN** [comment]
@darrickyee, this is more likely due to a SymbolServer bug (possibly fixed).

A large number of the missing Base references are due to the non-relative path respecting internal `include` method. I just need to work out the least offensive hacky approach to handling this. A large share of the remaining (e.g. trig functions) are defined through use of `eval`. I have a pseudo-interpreting approach in mind but it needs a bit more thinking through

**Comment by darrickyee** [comment]
Ok, thanks for the update, @ZacLN!  Will stay tuned for updates.

**Comment by tribut** [comment]
Just ran into `Main` not being resolved;

![main-reference](https://user-images.githubusercontent.com/719105/66401871-2be8c080-e9e4-11e9-9be0-bacb0d7e10ae.png)

Not sure if this is the same bug (but references to `Main` in Julia's source seem to be having the same problem), so I'm leaving this here as a reminder to check when the other problems are resolved.

**Comment by ZacLN** [comment]
I think we've captured all of these missing names (from Base and Core)

**Comment by mbaz** [comment]
I'm having this issue with `DelimitedFiles`.

**Comment by pierreglaser** [comment]
Hi, I'm having the exact same issue as mentioned in https://github.com/julia-vscode/julia-vscode/issues/794#issuecomment-517009578
